### ISSUE TITLE
Build wheels for TensorFlow Lite

### ISSUE THREAD

**Issue by kasitoru** [home-assistant/wheels-tensorflow#8]
Official **TensorFlow Lite** wheels for armhf don't work on Home Assistant OS:

```
Error loading shared library ld-linux-armhf.so.3: No such file or directory
```

Is it possible to build a working package with this?

**Comment by frenck** [comment]
Should be possible, but we have no need for it at this point. We are happy to receive contributions though.

In general, those things probably run better in an add-on.

**Comment by kasitoru** [comment]
Are there addons with TensorFlow Lite for ARM architectures?

**Comment by frenck** [comment]
Dunno for sure. DOODS maybe?

**Comment by kasitoru** [comment]
DOODS consumes too many resources. I have prepared [tools](https://github.com/avdeevsv91/tflite_runtime-musl) for cross-compiling `tflite_runtime` using musl libc. This works great on Home Assistant OS.
